export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const FETCH_PATIENT_REQUEST = "FETCH_PATIENT_REQUEST";
export const FETCH_PATIENT_SUCCESS = "FETCH_PATIENT_SUCCESS";
export const FETCH_PATIENT_FAILURE = "FETCH_PATIENT_FAILURE";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_CARTE_REQUEST = "FETCH_CARTE_REQUEST";
export const FETCH_CARTE_SUCCESS = "FETCH_CARTE_SUCCESS";
export const FETCH_CARTE_FAILURE = "FETCH_CARTE_FAILURE";

export const FETCH_PATIENT_TO_FILE_REQUEST = "FETCH_PATIENT_TO_FILE_REQUEST";
export const FETCH_PATIENT_TO_FILE_SUCCESS = "FETCH_PATIENT_TO_FILE_SUCCESS";
export const FETCH_PATIENT_TO_FILE_FAILURE = "FETCH_PATIENT_TO_FILE_FAILURE";

export const FETCH_DMP_RADIO_REQUEST = "FETCH_DMP_RADIO_REQUEST";
export const FETCH_DMP_RADIO_SUCCESS = "FETCH_DMP_RADIO_SUCCESS";
export const FETCH_DMP_RADIO_FAILURE = "FETCH_DMP_RADIO_FAILURE";



export const FETCH_DMP_BIO_REQUEST = "FETCH_DMP_BIO_REQUEST";
export const FETCH_DMP_BIO_SUCCESS = "FETCH_DMP_BIO_SUCCESS";
export const FETCH_DMP_BIO_FAILURE = "FETCH_DMP_BIO_FAILURE";


export const FETCH_DMP_HOSPITALISATION_REQUEST = "FETCH_DMP_HOSPITALISATION_REQUEST";
export const FETCH_DMP_HOSPITALISATION_SUCCESS = "FETCH_DMP_HOSPITALISATION_SUCCESS";
export const FETCH_DMP_HOSPITALISATION_FAILURE = "FETCH_DMP_HOSPITALISATION_FAILURE";



export const FETCH_DMP_CONSULTATION_REQUEST = "FETCH_DMP_CONSULTATION_REQUEST";
export const FETCH_DMP_CONSULTATION_SUCCESS = "FETCH_DMP_CONSULTATION_SUCCESS";
export const FETCH_DMP_CONSULTATION_FAILURE = "FETCH_DMP_CONSULTATION_FAILURE";