export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const FTCH_PATIENT_REQUEST = "FTCH_PATIENT_REQUEST";
export const FTCH_PATIENT_SUCCESS = "FTCH_PATIENT_SUCCESS";
export const FTCH_PATIENT_FAILURE = "FTCH_PATIENT_FAILURE";

